// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CompiledModels
{
    public partial class TierListDbContextModel
    {
        private TierListDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("c34c6578-bc7d-4b49-8b4f-37339bc77237"), entityTypeCount: 5)
        {
        }

        partial void Initialize()
        {
            var tierImageContainer = TierImageContainerEntityType.Create(this);
            var tierImageEntity = TierImageEntityEntityType.Create(this);
            var tierListEntity = TierListEntityEntityType.Create(this);
            var tierBackupRowEntity = TierBackupRowEntityEntityType.Create(this, tierImageContainer);
            var tierRowEntity = TierRowEntityEntityType.Create(this, tierImageContainer);

            TierImageContainerEntityType.CreateForeignKey1(tierImageContainer, tierListEntity);
            TierImageEntityEntityType.CreateForeignKey1(tierImageEntity, tierImageContainer);

            TierImageContainerEntityType.CreateAnnotations(tierImageContainer);
            TierImageEntityEntityType.CreateAnnotations(tierImageEntity);
            TierListEntityEntityType.CreateAnnotations(tierListEntity);
            TierBackupRowEntityEntityType.CreateAnnotations(tierBackupRowEntity);
            TierRowEntityEntityType.CreateAnnotations(tierRowEntity);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.6");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
