// <auto-generated />
using CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;
using TierList.Persistence.Postgres;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(TierListDbContext), typeof(TierListDbContextModel))]
